openapi: 3.0.3
info:
  version: 1.0.0
  title: 3040Crypto Wallet API
  description: |
    The 3040Crypto Wallet API is designed to provide a comprehensive suite of services for managing cryptocurrency wallets. It enables users to create new wallets, check balances, and view transaction histories, ensuring a seamless and user-friendly experience. This API aims to establish 3040Crypto as the premier choice for secure and efficient cryptocurrency management.
tags:
  - name: Account Management
    description: Operations related to accounts.
  - name: Wallet
    description: Operations related to cryptocurrency wallets.
servers:
  - url: https://api.3040crypto.com/v1
externalDocs:
    description: About us
    url: https://github.com/simkaurd/3040Crypto_noName
paths:
  /api/user/register:
    post:
      tags: 
      - Account Management
      summary: Register User
      description: Streamlines the process of registering new users by collecting necessary information.
      responses:
        '200':
          description: Account creation successful.
          content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/RegisterUserInput'
        '400':
            $ref: '#/components/responses/UserRegistrationUnsuccessful'
  /api/wallet/create:
    post:
      tags: 
      - Wallet
      summary: Create New Wallet
      description: Enables the creation of a new cryptocurrency wallet and provides a unique ID for the wallet for future usage.
      responses:
        '200':
          description: Wallet creation successful.
          content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/CreateWallet'
        '400':
            $ref: '#/components/responses/WalletCreationUnsuccessful'
  /api/wallet/balance:
    get:
      tags: 
      - Wallet
      summary: Get Wallet Balance
      description: Facilitates the retrieval of the current balance for a chosen cryptocurrency within the user's wallet, supporting effective financial oversight.
      parameters:
        - name: wallet_id
          in: query
          description: The unique identifier of the user's wallet.
          required: true
          schema:
            type: string
            example: 279129ade
        - name: currency
          in: query
          description: The specific cryptocurrency to check the balance for. Defaults to Bitcoin (BTC) if not specified.
          required: false
          schema:
            type: string
            example: BTC
      responses:
        '200':
          description: Retrieved wallet balance successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WalletBalance'
        '400':
          $ref: '#/components/responses/WalletBalanceUnsuccessful'

components:
  schemas:
    RegisterUserInput:
      type: object
      properties:
        username:
          type: string
          example: newUser123
        email:
          type: string
          example: newuser@example.com
        password:
          type: string
          example: aStrOngPass
        fullName:
          type: string
          example: Simran Kaur
        phoneNumber:
          type: string
          example: 9876543210
    CreateWallet:
      type: object
      properties:
        user_id:
          type: string
          example: 65373
        email:
          type: string
          example: sample@example.com
    WalletBalance:
      type: object
      properties:
        wallet_id:
          type: string
          example: usdiu37
        currency:
          type: string
          example: BTC
        balance:
          type: number
          example: 2755.89
  responses:
    UserRegistrationUnsuccessful:
      description: Bad request. Could not complete registration. Please verify input values.
    WalletCreationUnsuccessful:
      description: Bad request. Wallet could not be created.
    WalletBalanceUnsuccessful:
      description: Bad request. Please check your input values.
